import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

const brandColors = {
  primary: '#2e6155',
  primaryLight: '#3a7966',
  primaryDark: '#1e3a32',
  secondary: '#34d399',
  secondaryLight: '#6ee7b7',
  accent: '#3a7966',
  error: '#ef4444',
  warning: '#f59e0b',
  success: '#10b981',
  info: '#6366f1',
};

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.primary,
    primaryContainer: '#d1fae5',
    secondary: brandColors.secondary,
    secondaryContainer: '#ecfdf5',
    error: brandColors.error,
    errorContainer: '#fee2e2',
    background: '#f8fafc',
    surface: '#FFFFFF',
    surfaceVariant: '#f1f5f9',
    onPrimary: '#FFFFFF',
    onSecondary: '#FFFFFF',
    onBackground: '#1e293b',
    onSurface: '#1e293b',
    onSurfaceVariant: '#64748b',
    outline: '#e2e8f0',
    outlineVariant: '#f0f0f0',
    elevation: {
      level0: 'transparent',
      level1: '#FFFFFF',
      level2: '#f8fafc',
      level3: '#f1f5f9',
      level4: '#e2e8f0',
      level5: '#cbd5e1',
    },
  },
  custom: {
    ...brandColors,
    chatBubbleOut: '#dcf8c6',
    chatBubbleIn: '#FFFFFF',
    chatBackground: '#efeae2',
    unreadBadge: brandColors.primary,
    statusSent: '#9ca3af',
    statusDelivered: '#34d399',
    statusRead: '#2e6155',
    headerBackground: brandColors.primary,
    headerText: '#FFFFFF',
    tabBarBackground: '#FFFFFF',
    tabBarActive: brandColors.primary,
    tabBarInactive: '#9ca3af',
    divider: '#e2e8f0',
    cardBackground: '#FFFFFF',
    inputBackground: '#f1f5f9',
    placeholder: '#9ca3af',
    shadow: 'rgba(0, 0, 0, 0.08)',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: brandColors.primaryLight,
    primaryContainer: '#1e3a32',
    secondary: brandColors.secondaryLight,
    secondaryContainer: '#064e3b',
    error: '#f87171',
    errorContainer: '#991b1b',
    background: '#0f172a',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onBackground: '#e2e8f0',
    onSurface: '#e2e8f0',
    onSurfaceVariant: '#94a3b8',
    outline: '#475569',
    outlineVariant: '#334155',
    elevation: {
      level0: 'transparent',
      level1: '#1e293b',
      level2: '#253345',
      level3: '#2d3d50',
      level4: '#334155',
      level5: '#3b4a5e',
    },
  },
  custom: {
    ...brandColors,
    chatBubbleOut: '#005c4b',
    chatBubbleIn: '#202c33',
    chatBackground: '#0b141a',
    unreadBadge: brandColors.primaryLight,
    statusSent: '#64748b',
    statusDelivered: '#34d399',
    statusRead: '#6ee7b7',
    headerBackground: '#1e293b',
    headerText: '#FFFFFF',
    tabBarBackground: '#1e293b',
    tabBarActive: brandColors.primaryLight,
    tabBarInactive: '#64748b',
    divider: '#334155',
    cardBackground: '#1e293b',
    inputBackground: '#334155',
    placeholder: '#64748b',
    shadow: 'rgba(0, 0, 0, 0.3)',
  },
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const borderRadius = {
  sm: 4,
  md: 8,
  lg: 12,
  xl: 16,
  xxl: 24,
  full: 9999,
};

export const fontSize = {
  xs: 10,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 18,
  xxl: 22,
  xxxl: 28,
  title: 34,
};

export type AppTheme = typeof lightTheme;
